version: '3.8'
services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/orders

  frontend:
    build: ./frontend-app
    ports:
      - "8080:80"
    depends_on:
      - catalog-service
      - order-service

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  

volumes:
  mongo-data:
