apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - first-ingress-app.com
      secretName: tls-secret 
  rules:
    - host: first-ingress-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loadbalancer-nginx-external
                port:
                  number: 80
