apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: local-microservices
spec:
  selector:
    matchLabels:
      app: catalog-products
  template:
    metadata:
      labels:
        app: catalog-products
    spec:
      containers:
      - name: catalog-container
        image: maldini12/catalog-products
        ports:
        - containerPort: 3001
        env: 
        - name: REDIS_HOST 
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: local-microservices
spec:
  selector:
    app: catalog-products
  ports:
  - port: 3001
    targetPort: 3001

