apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: local-microservices
spec:
  selector:
    matchLabels:
      app: frontent-ui
  template:
    metadata:
      labels:
        app: frontent-ui
    spec:
      containers:
      - name: frontent-ui
        image: maldini12/frontend-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: local-microservices
spec:
  selector:
    app: frontent-ui
  ports:
  - port: 80
    targetPort: 80

