apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-nginx-service
  namespace: local-microservices
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
