apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: local-microservices
data:
  nginx.conf: |
    worker_processes 1; # Nombre de processus de travail

    events {
        worker_connections 1024;   # Nombre de connexions par processus
    }

    http {
        server {
            listen 80;

            location / {
                proxy_pass http://frontend-service:80;  
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_read_timeout 300s; # Augmenter le timeout de lecture 
                proxy_connect_timeout 300s; # Augmenter le timeout de connexion
            }

            location /api/products {
                proxy_pass http://catalog-service:3001;  
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /api/orders {
                proxy_pass http://order-service:3002;  
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
